spring:
  application:
    name: service-cart
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.192.129:8848
      config:
        server-addr: 192.168.192.129:8848
        file-extension: yaml
        shared-configs:
          - data-id: common.yaml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml
      - nacos:common.yaml