spring:
  application:
    name: service-search
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 124.220.39.95:8848
#        server-addr: 127.0.0.1:8848
      config:
        server-addr: 124.220.39.95:8848
#        server-addr: 127.0.0.1:8848
        file-extension: yaml
        shared-configs:
          - data-id: common.yaml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml
      - nacos:common.yaml
elasticsearch:
  host: 192.168.153.130
  port: 9200